ROTATE_SPEED = .3
EXTEND_SPEED = .4
STABILIZE_ACCURACY_RANGE_Y = 2
STABILIZE_ACCURACY_RANGE_Z = 3
AUTONOMOUS_MODE = 0
USE_PNEUMATICS = True

RIGHT_SOLENOID_ID = 11
LEFT_SOLENOID_ID = 14

SLOW_FIXED_SPEED = 0.4


PNEUMATICS_MODULE_ID = 7